### ISSUE TITLE
FLOWNoise compiling error

### ISSUE THREAD

**Issue by dil937** [byuflowlab/FLOWUnsteady#101]
When installing "Other Packages" in the installation manual, FLOWNoise doesn't get compiled. It gives the following error. 

✗ FLOWNoise
  31 dependencies successfully precompiled in 51 seconds (72 already precompiled)
  1 dependency errored. To see a full report either run `import Pkg; Pkg.precompile()` or load the package

Any idea how this can be solved? Thank you so much for any help.

**Comment by EdoAlvarezR** [comment]
This should have been fixed with the latest commit to Main in FLOWNoise. Could try adding FLOWNoise again and seeing if that fixed it?

**Comment by tobiokanobi** [comment]
I just ran into the same problem. Changing pyplot to 2.11.1 resolved this issue

] add PyPlot@2.11.1

**Comment by dil937** [comment]
Thanks! It worked!

**Comment by dingzhw** [comment]
> I just ran into the same problem. Changing pyplot to 2.11.1 resolved this issue
> 
> ] add PyPlot@2.11.1

Thank you, @tobiokanobi ,It works!
