### ISSUE TITLE
I want to change the values of f and g mentioned in the paper in the original code, how do I make the changes?

### ISSUE THREAD

**Issue by weijunsjtu** [byuflowlab/FLOWUnsteady#102]
I want to change the values of f and g mentioned in the paper in the original code, how do I make the changes?

**Comment by EdoAlvarezR** [comment]
The VPM formulation is being passed to the `run_simulation(...)` function here: [LINK](https://github.com/byuflowlab/FLOWUnsteady/blob/master/src/FLOWUnsteady_simulation.jl#L127), which defaults to [`FLOWVPM.rVPM`](https://github.com/byuflowlab/FLOWVPM.jl/blob/master/src/FLOWVPM.jl#L64). The default `rVPM` formulation is defined [here](https://github.com/byuflowlab/FLOWVPM.jl/blob/master/src/FLOWVPM.jl#L56) as

```julia
formulation_rVPM = FLOWVPM.ReformulatedVPM{FLOWVPM.RealFMM}(0, 1/5)
```

where 0 is the value of f and 1/5 is the value of g. To use an alternative formulation, simply change those values in the script you use for running your simulation as follows

```
import FLOWUnsteady as uns
import FLOWVPM as vpm

.
.
.

f =             # <----- Insert value here
g =             # <----- Insert value here
myVPMformulation = vpm.ReformulatedVPM{vpm.RealFMM}(f, g)
.
.
.
run_simulation(args...; optargs..., vpm_formulation=myVPMformulation)
```
