### ISSUE TITLE
Restart the simulation from an existing time step

### ISSUE THREAD

**Issue by philippmandl** [byuflowlab/FLOWUnsteady#103]
Dear All, 

I tried to restart one simulation from an existing time-step, from where the simulation should proceed on. What is currently happening, that I am facing an error which says in the end, that the keyword "result_file" is unsupported --> do you have any ideas or experience with restarting simulations? 

Many thanks!

**Comment by EdoAlvarezR** [comment]
Hi Philip!

As indicated [in the docs](https://flow.byu.edu/FLOWUnsteady/api/flowunsteady-run/), the name of the keyword is `restart_vpmfile`. You could also check that directly in the code here: [LINK](https://github.com/byuflowlab/FLOWUnsteady/blob/master/src/FLOWUnsteady_simulation.jl#L165-L167)

**Comment by philippmandl** [comment]
great, thank you very much!!
