### ISSUE TITLE
The tunable parameters in the Hub/Tip Loss Correction function

### ISSUE THREAD

**Issue by iforever-yh** [byuflowlab/FLOWUnsteady#107]
Dear all,

I have been studying examples of "rotor in hover", however, I am not very clear about how to determine the tunable parameters(t1, t2, t3, h1, h2, h3) in the Hub/Tip Loss Correction function. Are these parameters related to the geometry or working conditions of the blades?

Thanks for your response!

**Comment by EdoAlvarezR** [comment]
Hi! Please refer to this reply in the Discussions: [LINK](https://github.com/byuflowlab/FLOWUnsteady/discussions/98#discussioncomment-7105272)

I hope that helps!
