### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by JonathonBowen** [byuflowlab/FLOWUnsteady#116]
Hi! 

On the installation of FlowUnsteady I am receiving the following error:

ERROR: Unsatisfiable requirements detected for package VSPGeom [9b3f6a95]:
 VSPGeom [9b3f6a95] log:
 ├─VSPGeom [9b3f6a95] has no known versions!
 └─restricted to versions * by FLOWUnsteady [b491798d] — no versions left
   └─FLOWUnsteady [b491798d] log:
     ├─possible versions are: 3.3.0 or uninstalled
     └─FLOWUnsteady [b491798d] is fixed to version 3.3.0

I have tried my best to try and find a solution for this but to no avail. Any help on this final stage would be greatly appreciated! 

All the best, 
J.

**Comment by inse0918** [comment]
Hi, follow this contents.

## Other Packages
Run the following commands in the Julia REPL to add some dependencies that are not
in the official Julia registry:
```julia
import Pkg

url = "https://github.com/byuflowlab/"

packages = (("AirfoilPrep.jl", "v2.1.2"), ("FLOWVLM", "v2.1.2"),
            ("BPM.jl", "v2.0.1"), ("FLOWNoise", "v2.3.2"), ("VSPGeom.jl", nothing))

Thank you.

**Comment by JonathonBowen** [comment]
Thank you for your help!

**Comment by sakurakikiki** [comment]
> Hi, follow this contents.
> 
> ## Other Packages
> Run the following commands in the Julia REPL to add some dependencies that are not in the official Julia registry:
> 
> ```julia
> import Pkg
> 
> url = "https://github.com/byuflowlab/"
> 
> packages = (("AirfoilPrep.jl", "v2.1.2"), ("FLOWVLM", "v2.1.2"),
>             ("BPM.jl", "v2.0.1"), ("FLOWNoise", "v2.3.2"), ("VSPGeom.jl", nothing))
> ```

Hello, why does flowvlm fail to compile

**Comment by VE111** [comment]
I have the problem too. Can U solve it ?

**Comment by sakurakikiki** [comment]
> I have the problem too. Can U solve it ?

Dude, you can change python to 3.8 and give it a try
