### ISSUE TITLE
WOPWOP Sigma Surface

### ISSUE THREAD

**Issue by christianhauschel** [byuflowlab/FLOWUnsteady#132]
Hello

I have created a sigma surface output from WOPWOP (v3.5) from your rotorhover example:

![image](https://github.com/byuflowlab/FLOWUnsteady/assets/90248888/a26d3ac7-a258-4c64-a3c6-9824fa603e5f)

![image](https://github.com/byuflowlab/FLOWUnsteady/assets/90248888/b34dcb85-b26e-40cb-beab-cb2a0231a7de)

It looks like the tip elements of the blades are corrupted. 

By contrast, the VTK blades look perfect. The acoustic result also seems to look correct.

Have you ever faced a similar issue?

Best regards,
Christian

**Comment by AndreaRapi** [comment]
Hi Christian,
what operating system do you have?
Andrea

**Comment by AndreaRapi** [comment]
Okay, thank you. I am using Windows as well. Have you encountered a response similar to this when running WOPWOP (v3.5)? It seems to be stuck in a loop.
![Screenshot 2024-01-10 105639](https://github.com/byuflowlab/FLOWUnsteady/assets/148783703/2d1fdca0-d206-4472-9a95-fd865b019f07)

**Comment by EdoAlvarezR** [comment]
@christianhauschel, how did you create those surfaces from PSU-WOPWOP? Is that a feature in the new version? (v3.5)

@AndreaRapi has been running into issues with the new version, so I wonder if this is related.

**Comment by EdoAlvarezR** [comment]
Ah, you might have found the issue. Any chance you could reach out to the team at PSU developing PSU-WOPWOP for guidance on what they might have changed in the latest version that broke the geometry definition?

**Comment by EdoAlvarezR** [comment]
Thanks for jumping on that, @christianhauschel !

**Comment by AndreaRapi** [comment]
Hi @christianhauschel @EdoAlvarezR,

I contacted them too for the v3.4. I checked again the v3.5.0 with different cases and the problem is related to the Windows version. I did again the tests with the Linux version and about acoustics validation is working good. Let's wait for the v3.4. to compare it.

**Comment by AndreaRapi** [comment]
Thank you @christianhauschel!!!
