### ISSUE TITLE
Maneuver example informations

### ISSUE THREAD

**Issue by MarcoPic99** [byuflowlab/FLOWUnsteady#135]
Hi!

I was reading your eVTOL example, where you simulate a maneuver and i noticed that, for all the propellers, you read just one polar at a fixed Reynolds number. This means that the aerodynamics coefficients of the propellers are assumed constant during the maneuver, right? So, if i would take into account the aero coefficients variation i need to run xfoil or provide a different polar at each time step ? Or there is a different way to do that?

Thank you in advance!

**Comment by EdoAlvarezR** [comment]
Hi Marco! That is correct. The Reynolds number is assumed to be constant throughout the maneuver. 

Currently, there isn't a clean way of providing different polars for different time steps, but it can certainly be done if you are brave enough to manually modify [the polars](https://github.com/byuflowlab/FLOWVLM/blob/master/src/FLOWVLM_rotor.jl#L81-L84) at each time step inside a custom-defined runtime function.

**Comment by MarcoPic99** [comment]
Thank you very much !

Marco
