### ISSUE TITLE
Variable Fidelity - High fidelity tutorial

### ISSUE THREAD

**Issue by AndreaRapi** [byuflowlab/FLOWUnsteady#140]
I tried to simulate the High Fidelity DJI 9443 Rotorhover tutorial considering the following:

```
vpm_SFS       = vpm.DynamicSFS(vpm.Estr_fmm, vpm.pseudo3level_positive;
                                   alpha=0.999, maxC=1.0,
                                   clippings=[vpm.clipping_backscatter])
```

but after some iterations (800) Julia killed the process. Is there anything that can be done to fix the problem or understand why?

Thank you,
Andrea

**Comment by EdoAlvarezR** [comment]
The only thing I can think off is that perhaps you ran out of RAM and swap memory and your operative system killed the process because of this. You can check that by re-running the simulation while monitoring the RAM usage in your operative system (e.g., `htop` in Linux/MacOS, Task Manager in Windows)

**Comment by AndreaRapi** [comment]
Many thanks. I will do it.

**Comment by NM1293** [comment]
@AndreaRapi Hello Andrea.
Have you solved the problem?
Have you understood what it depends on?
I am facing the same problem with the high fidelity case, at iteration 1200.

Thank you.

**Comment by AndreaRapi** [comment]
@NM1293 Hi there,
I haven't run that case again because as already suggested it's related to the RAM limit, so I guess is related to the features of my PC. I don't know how to solve it honestly.

**Comment by NM1293** [comment]
@AndreaRapi Ok. Thank you for your reply.
