### ISSUE TITLE
Rotor in Hover

### ISSUE THREAD

**Issue by christianhauschel** [byuflowlab/FLOWUnsteady#150]
I am simulating a rotor in hover, so I created my script, inspired by the "Rotor in Hover" example.

However, for some reason, the induced velocity is in the wrong direction:
![image](https://github.com/byuflowlab/FLOWUnsteady/assets/90248888/97542885-a7b4-49e5-ba19-54fc8ea1f4c0)

![image](https://github.com/byuflowlab/FLOWUnsteady/assets/90248888/582b279c-3131-43d4-bf20-45dd9960aeef)

The blades are rotating in the correct direction in ParaView.

Why could this be?

I think it could have something do to with the twist (different signs of twist spline and data). In ParaView, the blades' twist angles look ok.
Why could the twist spline have a negative spline?

![image](https://github.com/byuflowlab/FLOWUnsteady/assets/90248888/b901d0ae-f319-407c-9531-d5536e93345d)

**Comment by EdoAlvarezR** [comment]
Hi Christian!

It's difficult to tell what's happening from the screenshots. Could you share the script that you are using to run the simulation along the files defining the rotor geometry?
