### ISSUE TITLE
How do i create airfoil and rotor geometry database using propeller geometry file

### ISSUE THREAD

**Issue by Ajaykrishna0703** [byuflowlab/FLOWUnsteady#157]
Hello everyone 
I am a new user of FLOWUnsteady. I have a propeller geometry in STEP format. FLOWUnsteady requires a database of airfoil and rotor geometries to automate the generation of rotors. Can you suggest a way for me to obtain the required data for my propeller geometry using the STEP file?

**Comment by EdoAlvarezR** [comment]
Discussion continued in #158
