### ISSUE TITLE
Issues importing FLOWUnsteady package receiving a NULL PyObject error

### ISSUE THREAD

**Issue by mortimer-pc** [byuflowlab/FLOWUnsteady#179]
I have followed the installation instructions and have not had any issues until trying to import the FLOWUnsteady package to run some of the example cases. I am receiving a NULL PyObject LoadError during the precompilation.  Please see attached screenshot with details on the error. 

Please advise on a solution. 

![20240605 NULL PyObject Precompile Error](https://github.com/byuflowlab/FLOWUnsteady/assets/166747462/4ed24876-b0ed-46db-b9f9-0d87b7845894)

**Comment by Kalley2** [comment]
I'm experiencing the same problem, may I ask how you solved it?

**Comment by mortimer-pc** [comment]
Unfortunately, I have not solved it yet.

**Comment by cibinjoseph** [comment]
Adding a workaround for this. This is caused due to some weird incompatibility with PyPlot.
Commenting out [everything](https://github.com/byuflowlab/FLOWUnsteady/blob/53e94a4a711239cabda0ede7d57e31a294f8a47c/src/FLOWUnsteady_utils.jl#L29) inside the `formatpyplot()` function in `src/FLOWUnsteady_utils.jl` should allow you to install it. This is only a hotfix for now until we figure out what exactly is going wrong.

**Comment by sakurakikiki** [comment]
> Adding a workaround for this. This is caused due to some weird incompatibility with PyPlot. Commenting out [everything](https://github.com/byuflowlab/FLOWUnsteady/blob/53e94a4a711239cabda0ede7d57e31a294f8a47c/src/FLOWUnsteady_utils.jl#L29) inside the `formatpyplot()` function in `src/FLOWUnsteady_utils.jl` should allow you to install it. This is only a hotfix for now until we figure out what exactly is going wrong.

Hello, why do I still have the following problem according to what you said
![image](https://github.com/byuflowlab/FLOWUnsteady/assets/171261193/8b326a84-1beb-4214-af45-8396966faf3b)

**Comment by EdoAlvarezR** [comment]
It's a little embarrassing that it took me so long to fix this (it literally took 30 seconds to push a fix), but, in my defense, I just had a baby ¯\\_(ツ)\_/¯.

As @cibinjoseph pointed out, `formatpyplot()` is the cause of the issue in the newer version of Julia (v1.10+), so [I commented out](https://github.com/byuflowlab/FLOWUnsteady/commit/e99e5e44144c0cb9f5621833a6a6c8adddb800e4) the call to `formatpyplot()` upon importing FLOWUnsteady. I had fixed that in my current feature dev branch, but it hadn't make its way to dev and master yet.
