### ISSUE TITLE
FLOWUnsteady compiled failure!

### ISSUE THREAD

**Issue by sakurakikiki** [byuflowlab/FLOWUnsteady#184]
2 dependencies successfully precompiled in 21 seconds. 284 already precompiled.
  1 dependency failed but may be precompilable after restarting julia
  1 dependency had output during precompilation:
![image](https://github.com/byuflowlab/FLOWUnsteady/assets/171261193/07182813-853d-48e0-8158-cacbbcac724c)

**Comment by EdoAlvarezR** [comment]
This seems to be an issue with Julia v1.10+. It stems from the fact that FLOWExaFMM uses a shared library that needs to be compiled manually. It is not an issue, but rather an observation.

**Comment by sakurakikiki** [comment]
> This seems to be an issue with Julia v1.10+. It stems from the fact that FLOWExaFMM uses a shared library that needs to be compiled manually. It is not an error, but rather a warning, so you are good to continue running the code.

Yes, you are absolutely right, I am up and running now
