### ISSUE TITLE
Install instructions: non-existent repo

### ISSUE THREAD

**Issue by willjrh** [byuflowlab/FLOWUnsteady#2]
In the 'instructions-setup.md'; it is instructed to:

### Getting airfoil
To get airfoil, clone the repo (not in Julia) and put it somewhere good for you

```git clone https://github.com/EdoAlvarezR/airfoil.git```

^ the above repo does not exist. I tried using AirfoilPrep. But I could not get this to work.

**Comment by EdoAlvarezR** [comment]
Installation instructions have been updated here: https://flow.byu.edu/FLOWUnsteady/tutorials/getting-started/
