### ISSUE TITLE
FlowUnsteady Example Error in JULIA on Windows

### ISSUE THREAD

**Issue by Koensig** [byuflowlab/FLOWUnsteady#24]
![image](https://user-images.githubusercontent.com/52273697/97919387-9f781100-1d4f-11eb-8466-3fad37db81d2.png)

I'm getting this error when trying to run the tandem heaving wing example. I'm assuming it's a file permission issue but I've given the directory read-write access so I'm not sure.

**Comment by EdoAlvarezR** [comment]
I pushed a fix to GeometricTools just now. Try updating GeometricTools (remove and re-add the package).

**Comment by Koensig** [comment]
That seems to have fixed it. Thanks.
