### ISSUE TITLE
Details missing concerning inputs to extra_runtime_functions

### ISSUE THREAD

**Issue by juddmehr** [byuflowlab/FLOWUnsteady#33]
It might be nice to put in the [Docs](https://flow.byu.edu/FLOWUnsteady/how-to-guide/set-up-runtime-functions/) that the time and time step passed into the extra_runtime_function is dimensional rather than non-dimensional time.

It can be a little confusing when all the simulation/maneuver inputs are defined in non-dimensional time, then any extra_runtime_functions have dimensional time passed in.  (This is not a bad thing in and of itself, just confusing if you don't know).

Along those lines, it might be good to explain all the inputs to the extra_runtime_function somewhere.

**Comment by EdoAlvarezR** [comment]
Implemented this in the new version of the docs: https://flow.byu.edu/FLOWUnsteady/api/flowunsteady-run
Thanks for the feedback!
