### ISSUE TITLE
[ERROR: LoadError: ExaFMM unexpected error: StackOverflowError()] in vahana.jl

### ISSUE THREAD

**Issue by inse0918** [byuflowlab/FLOWUnsteady#69]
Hi, all.

When I changed the vlm_vortexsheet option from 'false' to 'true' to activate ASM.

    *************************************************************************
    START vahana-example/vahana_pfield
            2023-05-25T11:09:03.401
    *************************************************************************
            Time step 0 out of 100  Particles: 0
                    Cd mean, stddev, ratio zeroes:  (NaN, NaN, NaN)
    ERROR: LoadError: ExaFMM unexpected error: StackOverflowError()

The code does not running.

How can I run this code with using ASM ?

Actually, I wanna write the Propeller-wing Interaction script by using ASM.

So, I refer the blownwing.jl applying the ASM contents, but the code is not running...

Anybody got script about the propeller-wing interaction using ASM ?

Thank you
Best regards,
Inseo

**Comment by inse0918** [comment]
Hi, @EdoAlvarezR 

I could not found the exact cause about this error.
Actually, the reason why I posted the question about the ASM is to analysis the propeller-wing interaction.
Anyway, I resolved the problem using original vahana.jl code.

I changed the vahana.jl to PROWIM validation code.
But the result is not similar with your validation data
![image](https://github.com/byuflowlab/FLOWUnsteady/assets/93040154/85d7229d-ff28-4b59-a557-b9b641e74799)

My data is,
![image](https://github.com/byuflowlab/FLOWUnsteady/assets/93040154/1d7ae9ba-4d81-47ec-965f-b8ef5560db42)

The section cl in the wing root is very low.

If you don't mind, could you please check my PROWIM code ?

or, could you please share your PROWIM validation data or code ?

Thank you.
Best regards,
Inseo.

[vahana.zip](https://github.com/byuflowlab/FLOWUnsteady/files/11682770/vahana.zip)

**Comment by inse0918** [comment]
Hi, @tim-chron .

I'm glad that you resolved the stackoverflow problem.

I also have the script that analysis the multi-rotor or propeller as you said.

You can handle the number of the propeller which have specific position, angle and phase angle.

Here is my script.

I hope you earn data what you want.

Thank you.
Best regards,
Inseo.

[PropMaster.zip](https://github.com/byuflowlab/FLOWUnsteady/files/11682812/PropMaster.zip)

**Comment by EvenW254** [comment]
> [@inse0918](https://github.com/inse0918), any chance you could share how you resolved the problem?


It may be "WAKE TREATMENT".
I meet the same question, I solved it by changing "minmaxGamma".
