### ISSUE TITLE
Actuator Surface Model with Propeller wing Interaction

### ISSUE THREAD

**Issue by inse0918** [byuflowlab/FLOWUnsteady#78]
Hi, I'm running the propeller wing interaction script.

I used the Actuator Surface Model on the wing.

Then, I used the Actuator Line Model on the propellers(beaver with 4 blades).

The script is going well.

The single wing and single propeller was validated using this script.

But the issue is the when the propeller with wing case(PROWIM Veldhuis) is not fitted with the wind tunnel testing results.

This is the single validation cases with using this script.

![image](https://github.com/byuflowlab/FLOWUnsteady/assets/93040154/68ad197d-09e3-4497-93a5-38754736a6c4) 
![image](https://github.com/byuflowlab/FLOWUnsteady/assets/93040154/091891ff-044c-4052-b0a8-195187bdaff9)

And this is the validation results about PROWIM propeller wing interaction (4 deg, J=0.85, RPM=14,800).

![image](https://github.com/byuflowlab/FLOWUnsteady/assets/93040154/649c4a90-39b1-4dd8-9ff7-b296e2d567b2)

The effect of the up-wash looks too much.

Is there a results that someone has it been validated ?

Thank you.
Best regards,
Inseo

[PWI.zip](https://github.com/byuflowlab/FLOWUnsteady/files/11999506/PWI.zip)

**Comment by EdoAlvarezR** [comment]
Hi @inse0918! This is a late reply and probably you already figured this out, but something to watchout for is that the PROWIM experiment used by Leo Veldhuis used a different thrust setting (CT=0.121 at J=0.85) that the what posterior studies reported with the isolated Beaver propeller. This leads to conclude that PROWIM used a collective pitch in the blade to achieve that thrust setting. See more details in [Sec. 8.4 of my dissertation](https://scholarsarchive.byu.edu/cgi/viewcontent.cgi?article=10598&context=etd):

![image](https://github.com/byuflowlab/FLOWUnsteady/assets/14857108/f6b267b3-723a-442f-bf4f-6b0a593bbddf)

Another thing: double check that the freestream matches the 49.5 m/s that they used in the experiment

**Comment by EdoAlvarezR** [comment]
Resolved in #129
