### ISSUE TITLE
After changing the parameters, the following error occurs when running

### ISSUE THREAD

**Issue by weijunsjtu** [byuflowlab/FLOWUnsteady#95]
After changing the parameters, the following error occurs when running
![image](https://github.com/byuflowlab/FLOWUnsteady/assets/143725166/3d3d4b65-86dd-415c-9a1e-5fb6f901a5a0)
The parameters I changed are as follows:
![image](https://github.com/byuflowlab/FLOWUnsteady/assets/143725166/11305239-0721-47e5-b7f6-73afcc47a408)
![image](https://github.com/byuflowlab/FLOWUnsteady/assets/143725166/0c3c68b9-cc42-4ba3-a369-e1f3b52bbd18)
n=20——>n=200
p_per_step=2——>p_per_step=72
Why this error occurs and how to solve it, thank you!

**Comment by EdoAlvarezR** [comment]
Hi! This means that the simulation blew up. Please see this discussion: #77
